### ISSUE TITLE
POJ104.io.tar.gz not found

### ISSUE THREAD

**Issue by DuckYellowPP** [rabbitjy/FuzzTuning#1]
The download address is invalid, can you share a new link?

Thank!

**Comment by xjzzzxx** [comment]
I met the same problem, looking forward to the processing of the authors

**Comment by rabbitjy** [comment]
Thanks for your interest. 

The link has been updated. Also,  the processed data at "./dataset" can be used directly.

**Comment by DuckYellowPP** [comment]
Thanks!
