### ISSUE TITLE
How to get original fuzz seed to input

### ISSUE THREAD

**Issue by Dojay6103** [rabbitjy/FuzzTuning#2]
This project is very amazing, but I would like to ask how to obtain the seed file of such a large amount of code?

**Comment by DataCorrupted** [comment]
Hi @Dojay6103 ! Thanks for the interest, hope you enjoyed our work! I am mainly responsible for data collection, and I can answer your questions.

But first let me clarify a few things, by "seed file" do you mean the initial seed, or the files after fuzzing?

- If you mean the initial seed, we crafted around 100 seeds by generating random text inputs, and these seeds are shared by all programs.
- If you mean seed collection after fuzzing, AFL++ dumps all the seed in a `queue` directory. We have a script to collect all of them after fuzzing.

**Comment by Dojay6103** [comment]
Thank you for your answer, what I want to ask about is the initial seed file. If it's convenient, could you tell me whether your randomly generated seed file is based on certain rules, so that it can be used as input for so many codes?

**Comment by DataCorrupted** [comment]
Motivation: the fuzzer needs an input that won't cause a crash to start. However, for programs in POJ104, inputs that doesn't fit into the format defined in the program will crash. Therefore, it is vital for us to provide seeds that fit the program's need.

The initial seed collection is roughly parsed as two stages:

We first randomly sampled 100 programs in POJ104 (0.2%) and reverse engineered their format (integer, float, string, etc.).
We use these formats to randomly generate text files.

After the first step, most of the programs can be fuzzed without problem (49068/50k = 94.36%). 
We further extended the initial seed by looking at the programs that couldn't initiate fuzzing and sampled another more programs.
In total, we have a little over 100 seeds.

Notice that for any specific program, many seeds are still invalid. There is no _one seed to fit them all_ scenario. However, as long as there is at least one seed in all seeds that can be used by the fuzzer, the fuzzer can take it from there to generate more valid inputs to explore the program. (The real power of fuzzing)
